=== venziait/Datalinks/venzia-datalink/src/main/resources/alfresco/schema/datalink.schema.json
{
 	"$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://aquacloud.venzia.es/schema/datalink.schema.json",
    "title": "Datalink",
    "type": "object",
 
    "properties": {
        "name": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "aspectName": {
            "type": "string",
            "description": "Alfresco aspect name"
        },
        "aspectPropertyName": {
            "type": "string",
            "description": "Alfresco property name of aspect the type text"
        },
        "order": {
         	"type": "integer",
         	"description": "Order in tab UI"
        },
        "connectorRest": {
            "type": "object",
            "description": "properties to service rest",
            "properties": {
            	"url": {
            		"type": "string"
            	},
            	"authentication": {
            		"type": "object",
            		"required": ["type"],
            		"properties": {
            			"type": {
            				"type": "string",
            				 "enum": ["none", "basic"]
            			},
            			"username":{
            				"type": "string"
            			},
            			"password": {
            				"type": "string"
            			}
            		},
            		"if": {
						    "properties": {
						      "type": {
						        "enum": ["basic"]
						      }
						    }
						  },
						  "then": {
						    "required": ["username","password"]
						  }
					},
            	"searchParam": {
            		"type": "string"
            	}
           }
        },
      
        "columns": {
        	"description": "Column list",
            "type": "array",
            "items": {
               "type": "object",
	            "required": ["primaryKey","name","type"],
	            "properties": {
			             "primaryKey": {
				              "type": "boolean"
				          },
			              "name": {
			                "type": "string"
			              },
			              "label": {
			                "type": "string"
			              },
			              "type": {
			                "type": "string"
			              },
			              "format": {
			                "type": "string"
			              },
			              "hidden": {
			                "type": "boolean"
			              }
	            }
            }
        }
    },
    "required": ["name", "aspectName","aspectPropertyName","connectorRest","order"]
}

=== venziait/Datalinks/venzia-datalink/src/main/docker/datalink/datalink-department.json
{
  "name":"departments",
  "title":"Company Departments",
  "description":"Example to datalink demo",
  "aspectName":"dlnk:departm",
  "aspectPropertyName":"dlnk:departm",
  "order":20,
  "connectorRest": {
    "url": "http://localhost:3005/api/v1/private/departments/search",
    "authentication": {
      "type":"basic",
      "username":"user2019",
      "password":"g3n3r4l"
    },
    "searchParam":"query"
  },
  "columns": [
    {
      "primaryKey":true,
      "name":"dept_no",
      "label":"Id",
      "type":"text",
      "hidden":true
    },
    {
      "primaryKey":false,
      "name":"dept_name",
      "label":"Name",
      "type":"text"
    }
  ]
}
